/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alif Rifky
 */
public class view_inputpupuk extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public view_inputpupuk() {
        initComponents();
    }

    public void setTable(DefaultTableModel tm) {
        jTable1.setModel(tm);
    }

    public void addinputListener(ActionListener listener) {
        btn_input.addActionListener(listener);
    }

    public String getInputA() {
        return inputa.getText();
    }

    public String getInputB() {
        return inputb.getText();
    }

    public String getInputC() {
        return inputc.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputa = new javax.swing.JTextField();
        inputb = new javax.swing.JTextField();
        inputc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_input = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputa.setText("0");
        inputa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputaActionPerformed(evt);
            }
        });
        getContentPane().add(inputa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        inputb.setText("0");
        getContentPane().add(inputb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, -1));

        inputc.setText("0");
        getContentPane().add(inputc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 280, 320));

        btn_input.setText("input");
        getContentPane().add(btn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_inputpupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_inputpupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_inputpupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_inputpupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_inputpupuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_input;
    private javax.swing.JTextField inputa;
    private javax.swing.JTextField inputb;
    private javax.swing.JTextField inputc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
